version: "3.9"

services:
  nvidia-container-runtime:
    container_name: nv-con-runtime
    image: nvidia/cuda:11.0-base
    runtime: nvidia
    privileged: true

    # devices:
    #   # - /dev:/dev
    #   - /dev/nvidia0:/dev/nvidia0
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-caps:/dev/nvidia-caps
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    #   - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    entrypoint: ["nvidia-smi"]

  nvidia-container-toolkit:
    container_name: nv-con-toolkit
    image: nvidia/cuda:11.0-base
    # privileged: true

    devices:
      # - /dev:/dev
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # equivalent for gpus = 1, if this is not set, gpus = all
              capabilities: [gpu]
    entrypoint: ["nvidia-smi"]

  recsys:
    container_name: recsys
    # # torch original image
    # this image suck due to poor C++ supporting
    # image: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel@sha256:9bfcfa72b6b244c1fbfa24864eec97fb29cfafc065999e9a9ba913fa1e690a02
    
    # # tensorflow original image
    # image: tensorflow/tensorflow:2.9.0rc0-gpu@sha256:256e05c30e769cd038afdee4e9f307c5c7c720065520cde8a5aaa98b0619842c

    # add some packages (pytorch, faiss, anaconda3, ...) then commit
    image: tensorflow/tensorflow:2.9.0rc0-gpu

    volumes:
      - ./requirement.txt:/recsys/requirement.txt:rw
      - ./model:/recsys/model:rw
      - ./prototype:/recsys/prototype:rw
      - ./data:/recsys/data:rw
      - ./notebook:/recsys/notebook:rw
      - ./container_share.log:/recsys/container_share.log:rw
    runtime: nvidia
    # privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      # - /dev:/dev
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    network_mode: "host"
    # networks:
    #   collaborative-recommender-network:
    #     ipv4_address: 128.0.1.2
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           # count: 1
    #           capabilities: [gpu]
    # entrypoint: ["nvidia-smi"]
    entrypoint: ["tail", "-f", "/recsys/container_share.log"]

networks:
  recsys-network:
    ipam:
      driver: default
      config:
        - subnet: "128.0.1.0/24"
