version: "3.9"

services:
  # nvidia-container-runtime:
  #   container_name: nv-con-runtime
  #   image: nvidia/cuda:11.0-base
  #   runtime: nvidia
  #   privileged: true

  #   # devices:
  #   #   # - /dev:/dev
  #   #   - /dev/nvidia0:/dev/nvidia0
  #   #   - /dev/nvidiactl:/dev/nvidiactl
  #   #   - /dev/nvidia-caps:/dev/nvidia-caps
  #   #   - /dev/nvidia-modeset:/dev/nvidia-modeset
  #   #   - /dev/nvidia-uvm:/dev/nvidia-uvm
  #   #   - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
  #   entrypoint: ["echo", "Service disabled"]

  # nvidia-container-toolkit:
  #   container_name: nv-con-toolkit
  #   image: nvidia/cuda:11.0-base
  #   # privileged: true

  #   devices:
  #     # - /dev:/dev
  #     - /dev/nvidia0:/dev/nvidia0
  #     - /dev/nvidiactl:/dev/nvidiactl
  #     - /dev/nvidia-caps:/dev/nvidia-caps
  #     - /dev/nvidia-modeset:/dev/nvidia-modeset
  #     - /dev/nvidia-uvm:/dev/nvidia-uvm
  #     - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1 # equivalent for gpus = 1, if this is not set, gpus = all
  #             capabilities: [gpu]
  #   entrypoint: ["echo", "Service disabled"]
  recsys:
    container_name: recsys
    # # torch original image
    # this image suck due to poor C++ supporting
    # image: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel@sha256:9bfcfa72b6b244c1fbfa24864eec97fb29cfafc065999e9a9ba913fa1e690a02

    # # tensorflow original image
    # image: tensorflow/tensorflow:2.9.0rc0-gpu@sha256:256e05c30e769cd038afdee4e9f307c5c7c720065520cde8a5aaa98b0619842c

    # build from tensorflow image, add some packages, spark + corretto8 + rapids
    image: mingkhoi/recsys:fixbug-version1
    volumes:
      - ./requirement.txt:/recsys/requirement.txt:rw
      - ./model:/recsys/model:rw
      - ./prototype:/recsys/prototype:rw
      - ./data:/recsys/data:rw
      - ./notebook:/recsys/notebook:rw
    # runtime: nvidia
    # privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      # - /dev:/dev
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    # network_mode: "host"
    ports:
      - "8080"
      - "8081"
      - "18080"
      - "7077"
      - "6066"
      - "7337"
      - "4040"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
    # entrypoint: ["nvidia-smi"]
    # entrypoint: ["tail", "-f", "/recsys/container_share.log"]
    entrypoint: ["tail", "-f", "/dev/null"]

  hdfs-namenode1:
    container_name: recsys-namenode1
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "9000" # default fs
      - "8020" # default namenode RPC port
      - "9870"
      - "9871"
      - "50100"
      - "50105"
      - "9868"
      - "9869"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.3
    volumes:
      - ./metadata/hdfs/namenode1:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/namenode1:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  hdfs-namenode2:
    container_name: recsys-namenode2
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "9000" # default fs
      - "8020" # default namenode RPC port
      - "9870"
      - "9871"
      - "50100"
      - "50105"
      - "9868"
      - "9869"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.4
    volumes:
      - ./metadata/hdfs/namenode2:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/namenode2:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  hdfs-resourcemanager:
    container_name: recsys-resourcemanager
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "8030"
      - "8032"
      - "8031"
      - "8033"
      - "8088"
      - "8090"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.5
    volumes:
      - ./metadata/hdfs/resource_manager:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/resource_manager:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  hdfs-datanode1:
    container_name: recsys-datanode1
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "9866"
      - "9864"
      - "9867"
      - "9865"
      - "8040"
      - "8048"
      - "8042"
      - "8044"
      - "8049"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.6
    volumes:
      - ./metadata/hdfs/datanode1:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/datanode1:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  hdfs-datanode2:
    container_name: recsys-datanode2
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "9866"
      - "9864"
      - "9867"
      - "9865"
      - "8040"
      - "8048"
      - "8042"
      - "8044"
      - "8049"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.7
    volumes:
      - ./metadata/hdfs/datanode2:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/datanode2:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  hdfs-datanode3:
    container_name: recsys-datanode3
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    ports:
      - "9866"
      - "9864"
      - "9867"
      - "9865"
      - "8040"
      - "8048"
      - "8042"
      - "8044"
      - "8049"
    networks:
      recsys-network:
        ipv4_address: 128.0.5.8
    volumes:
      - ./metadata/hdfs/datanode3:/home/hadoop/hdfs:rw
      - ./entry.sh:/entry.sh:rw
      - ./config/hdfs/datanode3:/opt/hadoop-3/etc/hadoop:rw
    entrypoint: ["/bin/sh", "-c", "/entry.sh"]

  build-hdfs:
    container_name: build-hdfs
    user: hadoop
    # ubuntu original image
    # image: ubuntu:18.04@sha256:512274f1739676880585e70eea6a883db7b6d92841b02647b6c92b478356572c

    # build from ubuntu image, add HDFS + corretto8
    image: mingkhoi/recsys-hdfs:fixbug-version1
    networks:
      recsys-network:
        ipv4_address: 128.0.5.9
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  recsys-network:
    name: recsys-network
    ipam:
      driver: default
      config:
        - subnet: "128.0.5.0/24"
