version: "3.9"

services:
  collaborative-recommender:
    container_name: collaborative-recommender
    image: mingkhoi/ubuntu-18.04-tensorrt7-tf1.15:version1.0
    volumes:
      - ./requirement.txt:/collaborative-recommender/requirement.txt:rw
      - ./src:/collaborative-recommender/src:rw
      - ./container_share.log:/container_share.log:rw
    runtime: nvidia
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    networks:
      collaborative-recommender-network:
        ipv4_address: 128.0.1.2
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: ["tail", "-f", "/container_share.log"]

networks:
  collaborative-recommender-network:
    ipam:
      driver: default
      config:
        - subnet: "128.0.1.0/24"
