import sys

sys.path.append("../../..")

from pprint import pprint
import numpy as np
import pandas as pd
from prototype.crawl_init_data.increase_id import cal_next_id

# each JSON is small, there's no need in iterative processing
import json
import sys
import os
import xml
import time

import pyspark
from pyspark.conf import SparkConf
from pyspark.context import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, LongType, IntegerType, FloatType

import copy
import uuid

os.environ["JAVA_HOME"] = "/opt/corretto-8"
os.environ["HADOOP_CONF_DIR"] = "/recsys/prototype/spark_submit/hdfs_cfg"

JAVA_LIB = "/opt/corretto-8/lib"

spark = SparkSession.builder \
    .config("spark.app.name", "Recsys") \
    .config("spark.master", "local[*]") \
    .config("spark.submit.deployMode", "client") \
    .config("spark.yarn.appMasterEnv.SPARK_HOME", "/opt/spark") \
    .config("spark.yarn.appMasterEnv.PYSPARK_PYTHON", "/virtual/python/bin/python") \
    .config("spark.yarn.jars", "hdfs://128.0.5.3:9000/lib/java/spark/jars/*.jar") \
    .config("spark.sql.legacy.allowNonEmptyLocationInCTAS", "true") \
    .getOrCreate()

coauthor_schema = StructType([       
    StructField('_id', StringType(), False),
    StructField('_status', IntegerType(), False),
    StructField('_timestamp', LongType(), False),
    StructField('paper_id', StringType(), False),
    StructField('paper_title', StringType(), False),
    StructField('author1_id', StringType(), False),
    StructField('author1_name', StringType(), False),
    StructField('author1_org', StringType(), False),
    StructField('author2_id', StringType(), False),
    StructField('author2_name', StringType(), False),
    StructField('author2_org', StringType(), False),
    StructField('year', FloatType(), False),
])
merge_df = spark.read.schema(coauthor_schema) \
    .parquet(
        "/data/recsys/arnet/tables/coauthor/production/part-0",
        "/data/recsys/arnet/tables/coauthor/production/part-1",
        "/data/recsys/arnet/tables/coauthor/production/part-10",
        "/data/recsys/arnet/tables/coauthor/production/part-100",
        "/data/recsys/arnet/tables/coauthor/production/part-101",
        "/data/recsys/arnet/tables/coauthor/production/part-102",
        "/data/recsys/arnet/tables/coauthor/production/part-103",
        "/data/recsys/arnet/tables/coauthor/production/part-104",
        "/data/recsys/arnet/tables/coauthor/production/part-105",
        "/data/recsys/arnet/tables/coauthor/production/part-106",
        "/data/recsys/arnet/tables/coauthor/production/part-107",
        "/data/recsys/arnet/tables/coauthor/production/part-108",
        "/data/recsys/arnet/tables/coauthor/production/part-109",
        "/data/recsys/arnet/tables/coauthor/production/part-11",
        "/data/recsys/arnet/tables/coauthor/production/part-110",
        "/data/recsys/arnet/tables/coauthor/production/part-111",
        "/data/recsys/arnet/tables/coauthor/production/part-112",
        "/data/recsys/arnet/tables/coauthor/production/part-113",
        "/data/recsys/arnet/tables/coauthor/production/part-114",
        "/data/recsys/arnet/tables/coauthor/production/part-115",
        "/data/recsys/arnet/tables/coauthor/production/part-116",
        "/data/recsys/arnet/tables/coauthor/production/part-117",
        "/data/recsys/arnet/tables/coauthor/production/part-118",
        "/data/recsys/arnet/tables/coauthor/production/part-119",
        "/data/recsys/arnet/tables/coauthor/production/part-12",
        "/data/recsys/arnet/tables/coauthor/production/part-120",
        "/data/recsys/arnet/tables/coauthor/production/part-121",
        "/data/recsys/arnet/tables/coauthor/production/part-122",
        "/data/recsys/arnet/tables/coauthor/production/part-123",
        "/data/recsys/arnet/tables/coauthor/production/part-124",
        "/data/recsys/arnet/tables/coauthor/production/part-125",
        "/data/recsys/arnet/tables/coauthor/production/part-126",
        "/data/recsys/arnet/tables/coauthor/production/part-127",
        "/data/recsys/arnet/tables/coauthor/production/part-128",
        "/data/recsys/arnet/tables/coauthor/production/part-129",
        "/data/recsys/arnet/tables/coauthor/production/part-13",
        "/data/recsys/arnet/tables/coauthor/production/part-130",
        "/data/recsys/arnet/tables/coauthor/production/part-131",
        "/data/recsys/arnet/tables/coauthor/production/part-132",
        "/data/recsys/arnet/tables/coauthor/production/part-133",
        "/data/recsys/arnet/tables/coauthor/production/part-134",
        "/data/recsys/arnet/tables/coauthor/production/part-135",
        "/data/recsys/arnet/tables/coauthor/production/part-136",
        "/data/recsys/arnet/tables/coauthor/production/part-137",
        "/data/recsys/arnet/tables/coauthor/production/part-138",
        "/data/recsys/arnet/tables/coauthor/production/part-139",
        "/data/recsys/arnet/tables/coauthor/production/part-14",
        "/data/recsys/arnet/tables/coauthor/production/part-140",
        "/data/recsys/arnet/tables/coauthor/production/part-141",
        "/data/recsys/arnet/tables/coauthor/production/part-142",
        "/data/recsys/arnet/tables/coauthor/production/part-143",
        "/data/recsys/arnet/tables/coauthor/production/part-144",
        "/data/recsys/arnet/tables/coauthor/production/part-145",
        "/data/recsys/arnet/tables/coauthor/production/part-146",
        "/data/recsys/arnet/tables/coauthor/production/part-147",
        "/data/recsys/arnet/tables/coauthor/production/part-148",
        "/data/recsys/arnet/tables/coauthor/production/part-149",
        "/data/recsys/arnet/tables/coauthor/production/part-15",
        "/data/recsys/arnet/tables/coauthor/production/part-150",
        "/data/recsys/arnet/tables/coauthor/production/part-151",
        "/data/recsys/arnet/tables/coauthor/production/part-152",
        "/data/recsys/arnet/tables/coauthor/production/part-153",
        "/data/recsys/arnet/tables/coauthor/production/part-154",
        "/data/recsys/arnet/tables/coauthor/production/part-155",
        "/data/recsys/arnet/tables/coauthor/production/part-156",
        "/data/recsys/arnet/tables/coauthor/production/part-157",
        "/data/recsys/arnet/tables/coauthor/production/part-158",
        "/data/recsys/arnet/tables/coauthor/production/part-159",
        "/data/recsys/arnet/tables/coauthor/production/part-16",
        "/data/recsys/arnet/tables/coauthor/production/part-160",
        "/data/recsys/arnet/tables/coauthor/production/part-161",
        "/data/recsys/arnet/tables/coauthor/production/part-162",
        "/data/recsys/arnet/tables/coauthor/production/part-163",
        "/data/recsys/arnet/tables/coauthor/production/part-164",
        "/data/recsys/arnet/tables/coauthor/production/part-165",
        "/data/recsys/arnet/tables/coauthor/production/part-166",
        "/data/recsys/arnet/tables/coauthor/production/part-167",
        "/data/recsys/arnet/tables/coauthor/production/part-168",
        "/data/recsys/arnet/tables/coauthor/production/part-169",
        "/data/recsys/arnet/tables/coauthor/production/part-17",
        "/data/recsys/arnet/tables/coauthor/production/part-170",
        "/data/recsys/arnet/tables/coauthor/production/part-171",
        "/data/recsys/arnet/tables/coauthor/production/part-172",
        "/data/recsys/arnet/tables/coauthor/production/part-173",
        "/data/recsys/arnet/tables/coauthor/production/part-174",
        "/data/recsys/arnet/tables/coauthor/production/part-175",
        "/data/recsys/arnet/tables/coauthor/production/part-176",
        "/data/recsys/arnet/tables/coauthor/production/part-177",
        "/data/recsys/arnet/tables/coauthor/production/part-178",
        "/data/recsys/arnet/tables/coauthor/production/part-179",
        "/data/recsys/arnet/tables/coauthor/production/part-18",
        "/data/recsys/arnet/tables/coauthor/production/part-180",
        "/data/recsys/arnet/tables/coauthor/production/part-181",
        "/data/recsys/arnet/tables/coauthor/production/part-182",
        "/data/recsys/arnet/tables/coauthor/production/part-183",
        "/data/recsys/arnet/tables/coauthor/production/part-184",
        "/data/recsys/arnet/tables/coauthor/production/part-185",
        "/data/recsys/arnet/tables/coauthor/production/part-186",
        "/data/recsys/arnet/tables/coauthor/production/part-187",
        "/data/recsys/arnet/tables/coauthor/production/part-188",
        "/data/recsys/arnet/tables/coauthor/production/part-189",
        "/data/recsys/arnet/tables/coauthor/production/part-19",
        "/data/recsys/arnet/tables/coauthor/production/part-190",
        "/data/recsys/arnet/tables/coauthor/production/part-191",
        "/data/recsys/arnet/tables/coauthor/production/part-192",
        "/data/recsys/arnet/tables/coauthor/production/part-193",
        "/data/recsys/arnet/tables/coauthor/production/part-194",
        "/data/recsys/arnet/tables/coauthor/production/part-195",
        "/data/recsys/arnet/tables/coauthor/production/part-196",
        "/data/recsys/arnet/tables/coauthor/production/part-197",
        "/data/recsys/arnet/tables/coauthor/production/part-198",
        "/data/recsys/arnet/tables/coauthor/production/part-199",
        "/data/recsys/arnet/tables/coauthor/production/part-2",
        "/data/recsys/arnet/tables/coauthor/production/part-20",
        "/data/recsys/arnet/tables/coauthor/production/part-200",
        "/data/recsys/arnet/tables/coauthor/production/part-201",
        "/data/recsys/arnet/tables/coauthor/production/part-202",
        "/data/recsys/arnet/tables/coauthor/production/part-203",
        "/data/recsys/arnet/tables/coauthor/production/part-204",
        "/data/recsys/arnet/tables/coauthor/production/part-205",
        "/data/recsys/arnet/tables/coauthor/production/part-206",
        "/data/recsys/arnet/tables/coauthor/production/part-207",
        "/data/recsys/arnet/tables/coauthor/production/part-208",
        "/data/recsys/arnet/tables/coauthor/production/part-209",
        "/data/recsys/arnet/tables/coauthor/production/part-21",
        "/data/recsys/arnet/tables/coauthor/production/part-210",
        "/data/recsys/arnet/tables/coauthor/production/part-211",
        "/data/recsys/arnet/tables/coauthor/production/part-212",
        "/data/recsys/arnet/tables/coauthor/production/part-213",
        "/data/recsys/arnet/tables/coauthor/production/part-214",
        "/data/recsys/arnet/tables/coauthor/production/part-215",
        "/data/recsys/arnet/tables/coauthor/production/part-216",
        "/data/recsys/arnet/tables/coauthor/production/part-217",
        "/data/recsys/arnet/tables/coauthor/production/part-218",
        "/data/recsys/arnet/tables/coauthor/production/part-219",
        "/data/recsys/arnet/tables/coauthor/production/part-22",
        "/data/recsys/arnet/tables/coauthor/production/part-220",
        "/data/recsys/arnet/tables/coauthor/production/part-221",
        "/data/recsys/arnet/tables/coauthor/production/part-222",
        "/data/recsys/arnet/tables/coauthor/production/part-223",
        "/data/recsys/arnet/tables/coauthor/production/part-224",
        "/data/recsys/arnet/tables/coauthor/production/part-225",
        "/data/recsys/arnet/tables/coauthor/production/part-226",
        "/data/recsys/arnet/tables/coauthor/production/part-227",
        "/data/recsys/arnet/tables/coauthor/production/part-228",
        "/data/recsys/arnet/tables/coauthor/production/part-229",
        "/data/recsys/arnet/tables/coauthor/production/part-23",
        "/data/recsys/arnet/tables/coauthor/production/part-230",
        "/data/recsys/arnet/tables/coauthor/production/part-231",
        "/data/recsys/arnet/tables/coauthor/production/part-232",
        "/data/recsys/arnet/tables/coauthor/production/part-233",
        "/data/recsys/arnet/tables/coauthor/production/part-234",
        "/data/recsys/arnet/tables/coauthor/production/part-235",
        "/data/recsys/arnet/tables/coauthor/production/part-236",
        "/data/recsys/arnet/tables/coauthor/production/part-237",
        "/data/recsys/arnet/tables/coauthor/production/part-238",
        "/data/recsys/arnet/tables/coauthor/production/part-239",
        "/data/recsys/arnet/tables/coauthor/production/part-24",
        "/data/recsys/arnet/tables/coauthor/production/part-240",
        "/data/recsys/arnet/tables/coauthor/production/part-241",
        "/data/recsys/arnet/tables/coauthor/production/part-242",
        "/data/recsys/arnet/tables/coauthor/production/part-243",
        "/data/recsys/arnet/tables/coauthor/production/part-244",
        "/data/recsys/arnet/tables/coauthor/production/part-245",
        "/data/recsys/arnet/tables/coauthor/production/part-246",
        "/data/recsys/arnet/tables/coauthor/production/part-247",
        "/data/recsys/arnet/tables/coauthor/production/part-248",
        "/data/recsys/arnet/tables/coauthor/production/part-249",
        "/data/recsys/arnet/tables/coauthor/production/part-25",
        "/data/recsys/arnet/tables/coauthor/production/part-250",
        "/data/recsys/arnet/tables/coauthor/production/part-251",
        "/data/recsys/arnet/tables/coauthor/production/part-252",
        "/data/recsys/arnet/tables/coauthor/production/part-253",
        "/data/recsys/arnet/tables/coauthor/production/part-254",
        "/data/recsys/arnet/tables/coauthor/production/part-255",
        "/data/recsys/arnet/tables/coauthor/production/part-256",
        "/data/recsys/arnet/tables/coauthor/production/part-257",
        "/data/recsys/arnet/tables/coauthor/production/part-258",
        "/data/recsys/arnet/tables/coauthor/production/part-259",
        "/data/recsys/arnet/tables/coauthor/production/part-26",
        "/data/recsys/arnet/tables/coauthor/production/part-260",
        "/data/recsys/arnet/tables/coauthor/production/part-261",
        "/data/recsys/arnet/tables/coauthor/production/part-262",
        "/data/recsys/arnet/tables/coauthor/production/part-27",
        "/data/recsys/arnet/tables/coauthor/production/part-28",
        "/data/recsys/arnet/tables/coauthor/production/part-29",
        "/data/recsys/arnet/tables/coauthor/production/part-3",
        "/data/recsys/arnet/tables/coauthor/production/part-30",
        "/data/recsys/arnet/tables/coauthor/production/part-31",
        "/data/recsys/arnet/tables/coauthor/production/part-32",
        "/data/recsys/arnet/tables/coauthor/production/part-33",
        "/data/recsys/arnet/tables/coauthor/production/part-34",
        "/data/recsys/arnet/tables/coauthor/production/part-35",
        "/data/recsys/arnet/tables/coauthor/production/part-36",
        "/data/recsys/arnet/tables/coauthor/production/part-37",
        "/data/recsys/arnet/tables/coauthor/production/part-38",
        "/data/recsys/arnet/tables/coauthor/production/part-39",
        "/data/recsys/arnet/tables/coauthor/production/part-4",
        "/data/recsys/arnet/tables/coauthor/production/part-40",
        "/data/recsys/arnet/tables/coauthor/production/part-41",
        "/data/recsys/arnet/tables/coauthor/production/part-42",
        "/data/recsys/arnet/tables/coauthor/production/part-43",
        "/data/recsys/arnet/tables/coauthor/production/part-44",
        "/data/recsys/arnet/tables/coauthor/production/part-45",
        "/data/recsys/arnet/tables/coauthor/production/part-46",
        "/data/recsys/arnet/tables/coauthor/production/part-47",
        "/data/recsys/arnet/tables/coauthor/production/part-48",
        "/data/recsys/arnet/tables/coauthor/production/part-49",
        "/data/recsys/arnet/tables/coauthor/production/part-5",
        "/data/recsys/arnet/tables/coauthor/production/part-50",
        "/data/recsys/arnet/tables/coauthor/production/part-51",
        "/data/recsys/arnet/tables/coauthor/production/part-52",
        "/data/recsys/arnet/tables/coauthor/production/part-53",
        "/data/recsys/arnet/tables/coauthor/production/part-54",
        "/data/recsys/arnet/tables/coauthor/production/part-55",
        "/data/recsys/arnet/tables/coauthor/production/part-56",
        "/data/recsys/arnet/tables/coauthor/production/part-57",
        "/data/recsys/arnet/tables/coauthor/production/part-58",
        "/data/recsys/arnet/tables/coauthor/production/part-59",
        "/data/recsys/arnet/tables/coauthor/production/part-6",
        "/data/recsys/arnet/tables/coauthor/production/part-60",
        "/data/recsys/arnet/tables/coauthor/production/part-61",
        "/data/recsys/arnet/tables/coauthor/production/part-62",
        "/data/recsys/arnet/tables/coauthor/production/part-63",
        "/data/recsys/arnet/tables/coauthor/production/part-64",
        "/data/recsys/arnet/tables/coauthor/production/part-65",
        "/data/recsys/arnet/tables/coauthor/production/part-66",
        "/data/recsys/arnet/tables/coauthor/production/part-67",
        "/data/recsys/arnet/tables/coauthor/production/part-68",
        "/data/recsys/arnet/tables/coauthor/production/part-69",
        "/data/recsys/arnet/tables/coauthor/production/part-7",
        "/data/recsys/arnet/tables/coauthor/production/part-70",
        "/data/recsys/arnet/tables/coauthor/production/part-71",
        "/data/recsys/arnet/tables/coauthor/production/part-72",
        "/data/recsys/arnet/tables/coauthor/production/part-73",
        "/data/recsys/arnet/tables/coauthor/production/part-74",
        "/data/recsys/arnet/tables/coauthor/production/part-75",
        "/data/recsys/arnet/tables/coauthor/production/part-76",
        "/data/recsys/arnet/tables/coauthor/production/part-77",
        "/data/recsys/arnet/tables/coauthor/production/part-78",
        "/data/recsys/arnet/tables/coauthor/production/part-79",
        "/data/recsys/arnet/tables/coauthor/production/part-8",
        "/data/recsys/arnet/tables/coauthor/production/part-80",
        "/data/recsys/arnet/tables/coauthor/production/part-81",
        "/data/recsys/arnet/tables/coauthor/production/part-82",
        "/data/recsys/arnet/tables/coauthor/production/part-83",
        "/data/recsys/arnet/tables/coauthor/production/part-84",
        "/data/recsys/arnet/tables/coauthor/production/part-85",
        "/data/recsys/arnet/tables/coauthor/production/part-86",
        "/data/recsys/arnet/tables/coauthor/production/part-87",
        "/data/recsys/arnet/tables/coauthor/production/part-88",
        "/data/recsys/arnet/tables/coauthor/production/part-89",
        "/data/recsys/arnet/tables/coauthor/production/part-9",
        "/data/recsys/arnet/tables/coauthor/production/part-90",
        "/data/recsys/arnet/tables/coauthor/production/part-91",
        "/data/recsys/arnet/tables/coauthor/production/part-92",
        "/data/recsys/arnet/tables/coauthor/production/part-93",
        "/data/recsys/arnet/tables/coauthor/production/part-94",
        "/data/recsys/arnet/tables/coauthor/production/part-95",
        "/data/recsys/arnet/tables/coauthor/production/part-96",
        "/data/recsys/arnet/tables/coauthor/production/part-97",
        "/data/recsys/arnet/tables/coauthor/production/part-98",
        "/data/recsys/arnet/tables/coauthor/production/part-99"
    )

merge_df.createOrReplaceTempView("coauthor_merge")

new_df = spark.sql("""
    select 
        cam._id,
        cam._status,
        cam._timestamp,
        cam.paper_id,
        cam.paper_title,
        cam.author1_id,
        cam.author1_name,
        cam.author1_org,
        cam.author2_id,
        cam.author2_name,
        cam.author2_org,
        cam.year
    from coauthor_merge as cam, 
        (select first_value(cam._id) as _id
            from coauthor_merge as cam
            group by cam.paper_id, cam.author1_id, cam.author2_id) as cau
    where cau._id = cam._id
""")

new_df.write.mode("overwrite") \
    .format("parquet").save(f"/data/recsys/arnet/tables/coauthor/production/merge-0")
